lemonbar & music: For once and for all it's simple and fast

diff --git a/bars/top_bar/_song b/bars/top_bar/_song
--- a/bars/top_bar/_song
+++ b/bars/top_bar/_song
@@ -7,17 +7,128 @@
 #   mpd
 #     mpc
 #
-# BeyondMagic © 2021
+# BeyondMagic  GPL3 LICENSE  2021
 
 
 # This source file will get two functions which are loaded every time you stop MPD
-#   See (https://github.com/BeyondMagic/config/blob/main/_desktop/status_info)
-#       (https://github.com/BeyondMagic/config/blob/main/_desktop/colours)
-. $HOME/desktop/status_info
+#   See (https://github.com/BeyondMagic/config/blob/main/Base/status_info)
+#       (https://github.com/BeyondMagic/config/blob/main/Base/colours)
 
+song_format() {
+  
+               info=$(mpc)
+               song=$(echo "$info" | head -n 1)
+        song_length=${#song}
+  max_length_scroll="$3"
 
-origin=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)
+   start_st="%%{F$1}"
+  middle_st="%%{F$2}"
 
+  [ ! -n $(pidof mpd) ] && {
+
+    # If the return value is not 0, then echo nothing, since mpd is not running
+    exit
+
+  } || {
+
+      # mpd is running, so find out if it's playing or paused and echo the
+      # corresponding glyph
+      echo "$info" | grep -q "playing" && {
+
+        sleep 0
+
+      } || {
+
+        printf "paused" &
+        exit
+
+      }
+
+  }
+
+  case "$max_length_scroll" in
+    ''|*[!0-9]*)
+      sleep 0
+    ;;
+    *)
+      [ "$song_length" -ge "$max_length_scroll" ] && {
+
+        songd="$(expr substr "$song" "$offset" "$max_length_scroll")"
+        [ "$songd" = "" ] || song="$songd"
+
+      }
+    ;;
+  esac
+
+  # Parse the info to get the progress in %
+  #   total=$(echo "$info" | sed -r "s/duration //;t;d")
+  #   progr=$(echo "$info" | sed -r "s/position //;t;d")
+  #   perc=$(awk -v n="$total" -v m="$progr" 'BEGIN{ print int(( m/n )*100) }')
+  perc=$(echo "$info" | grep -oie "([[:digit:]]*%)" | tr '%' ' ' | tr '(' ' ' | tr ')' ' ')
+  song_length=${#song}
+  perc_chr=$(awk -v n="$song_length" -v m="$perc" 'BEGIN{ print int( n*(m/100)) }')
+
+  #echo lol; exit
+
+  printf "$start_st$(expr substr "$song" 1 $perc_chr)$middle_st$(expr substr "$song" $(($perc_chr + 1)) $song_length)" &
+    
+}
+
+# Run formated song
+_run_song() {
+
+  song="$(song_format "$first_running_song_name" "$second_running_song_name" "$limit_extra_length")"
+
+  # dance loop
+  #  [ "$dance" = "$dance_r" ] && dance="$dance_l" || dance="$dance_r"
+ 
+	playlist="$(mpc playlist)"
+   current="$(mpc current)"
+    before="$(mpc playlist | grep -B1 "$current" | head -n 1)"
+     after="$(mpc queued)"
+
+  # No before?
+  [ "$before" ] || before=$(mpc playlist | grep -B1 -Ps "[-$current]" | head -n 1)
+
+  # If this is the first song of the playlist, then just outputs nothing as before
+	[ "$(echo "$playlist" | head -n1)" = "$current" ] && before="" || {
+
+    # Reduce length if it's bigger than 40 characters
+    [ ${#before} -gt $song_limit ] && before="$(echo "$before" | cut -c -$song_limit)..."
+
+  }
+
+  [ "$after" ] && after="$(echo "$after" | cut -c -$song_limit)..."
+
+  echo 'M' "%{T4 F$neighbors_fg}$before  %{T2 F$first_running_song_name}$song  %{T4 F$neighbors_fg}$after%{T1 F-}" &
+
+}
+
+# This function is called to continue the loop throughout the song
+#   It will be stopped/killed when MPD is stopped
+#   Funny enough the same script being looped here
+#   Is the one being used to stop this loop.
+_loop_song() {
+  
+  while :; do
+    
+    mpc current --wait >/dev/null 2>&1 || exit 1
+
+    # notify song
+    $origin/../mpd/song
+
+    _run_song
+
+  done &
+
+  while :; do
+  
+    _run_song
+    sleep 1
+
+  done &
+
+}
 
 # This function is the main one and will get the information of MPD
 #   It uses "mpc idleloop" method to gather MPD updates
@@ -25,21 +136,23 @@ origin=$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)
 #   however you need to edit the source code... which I'm
 #   not with the will to do.
 _music() {
+  
+  [ "$1" ] && origin="$1"
 
   mpc idleloop | \
     while IFS=$'\n' read -r new_change && read -r double_change; do
 
-    song=$($origin/mpd/__status "$first_running_song_name" \
-      "$second_running_song_name" "$limit_extra_length")
+    song="$(song_format "$first_running_song_name" \
+      "$second_running_song_name" "$limit_extra_length")"
 
     # if paused
     #   If paused, then stop loop function
     [ "$song" = "paused" ] && {
 
-      # stop song
-      pkill -KILL -f "__loop_status"; pkill -KILL -f "mpc\ current\ \-\-wait"
-      
-      echo 'M' "%{F$second_running_song_name} $extra_icon_paused %{F-}" &
+      pkill -P "$(pgrep -P $$ | tail -n1)"
+    
+      # save to archive
+      echo 'M' "%{F$second_running_song_name} $extra_icon_paused %{F-}"
 
     # if running
     #   If running, then continues the loop function
@@ -47,29 +160,29 @@ _music() {
 
       [ "$new_change" = 'mixer' ] && [ "$double_change" = 'mixer' ] && {
 
-        printf "Volume only\n"
+        #printf "Volume only\n"
+        sleep 0
 
       } || {
 
-        # stop song
-        pkill -KILL -f "__loop_status"
-
-        # run thes script
-        $origin/mpd/__loop_status &
+        pkill -P "$(pgrep -P $$ | tail -n1)"
+        _loop_song
 
       }
-
+    
     }
 
   done
 
   echo "- : •́ ◇ •̀ : -"; sleep 5
-  exec "$origin/_song"
+  exec "$origin/top_bar/_song" "$origin"
 
 }
 
+[ "$1" = "run" ] && {
 
-# Start
-_music
+  origin="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)/../"
+  . "$origin/config/colours"
+  _music "$origin"
 
-
+}
